# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/niina/greens_functions

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/niina/greens_functions

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/niina/greens_functions/CMakeFiles /home/niina/greens_functions/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/niina/greens_functions/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named greens_functions

# Build rule for target.
greens_functions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 greens_functions
.PHONY : greens_functions

# fast build rule for target.
greens_functions/fast:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/build
.PHONY : greens_functions/fast

#=============================================================================
# Target rules for targets named GreensFunction1DAbsAbs_test

# Build rule for target.
GreensFunction1DAbsAbs_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GreensFunction1DAbsAbs_test
.PHONY : GreensFunction1DAbsAbs_test

# fast build rule for target.
GreensFunction1DAbsAbs_test/fast:
	$(MAKE) -f tests/CMakeFiles/GreensFunction1DAbsAbs_test.dir/build.make tests/CMakeFiles/GreensFunction1DAbsAbs_test.dir/build
.PHONY : GreensFunction1DAbsAbs_test/fast

#=============================================================================
# Target rules for targets named GreensFunction1DRadAbs_test

# Build rule for target.
GreensFunction1DRadAbs_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GreensFunction1DRadAbs_test
.PHONY : GreensFunction1DRadAbs_test

# fast build rule for target.
GreensFunction1DRadAbs_test/fast:
	$(MAKE) -f tests/CMakeFiles/GreensFunction1DRadAbs_test.dir/build.make tests/CMakeFiles/GreensFunction1DRadAbs_test.dir/build
.PHONY : GreensFunction1DRadAbs_test/fast

#=============================================================================
# Target rules for targets named GreensFunction3DSym_test

# Build rule for target.
GreensFunction3DSym_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GreensFunction3DSym_test
.PHONY : GreensFunction3DSym_test

# fast build rule for target.
GreensFunction3DSym_test/fast:
	$(MAKE) -f tests/CMakeFiles/GreensFunction3DSym_test.dir/build.make tests/CMakeFiles/GreensFunction3DSym_test.dir/build
.PHONY : GreensFunction3DSym_test/fast

GreensFunction1DAbsAbs.o: GreensFunction1DAbsAbs.cpp.o
.PHONY : GreensFunction1DAbsAbs.o

# target to build an object file
GreensFunction1DAbsAbs.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction1DAbsAbs.cpp.o
.PHONY : GreensFunction1DAbsAbs.cpp.o

GreensFunction1DAbsAbs.i: GreensFunction1DAbsAbs.cpp.i
.PHONY : GreensFunction1DAbsAbs.i

# target to preprocess a source file
GreensFunction1DAbsAbs.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction1DAbsAbs.cpp.i
.PHONY : GreensFunction1DAbsAbs.cpp.i

GreensFunction1DAbsAbs.s: GreensFunction1DAbsAbs.cpp.s
.PHONY : GreensFunction1DAbsAbs.s

# target to generate assembly for a file
GreensFunction1DAbsAbs.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction1DAbsAbs.cpp.s
.PHONY : GreensFunction1DAbsAbs.cpp.s

GreensFunction1DAbsSinkAbs.o: GreensFunction1DAbsSinkAbs.cpp.o
.PHONY : GreensFunction1DAbsSinkAbs.o

# target to build an object file
GreensFunction1DAbsSinkAbs.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction1DAbsSinkAbs.cpp.o
.PHONY : GreensFunction1DAbsSinkAbs.cpp.o

GreensFunction1DAbsSinkAbs.i: GreensFunction1DAbsSinkAbs.cpp.i
.PHONY : GreensFunction1DAbsSinkAbs.i

# target to preprocess a source file
GreensFunction1DAbsSinkAbs.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction1DAbsSinkAbs.cpp.i
.PHONY : GreensFunction1DAbsSinkAbs.cpp.i

GreensFunction1DAbsSinkAbs.s: GreensFunction1DAbsSinkAbs.cpp.s
.PHONY : GreensFunction1DAbsSinkAbs.s

# target to generate assembly for a file
GreensFunction1DAbsSinkAbs.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction1DAbsSinkAbs.cpp.s
.PHONY : GreensFunction1DAbsSinkAbs.cpp.s

GreensFunction1DRadAbs.o: GreensFunction1DRadAbs.cpp.o
.PHONY : GreensFunction1DRadAbs.o

# target to build an object file
GreensFunction1DRadAbs.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction1DRadAbs.cpp.o
.PHONY : GreensFunction1DRadAbs.cpp.o

GreensFunction1DRadAbs.i: GreensFunction1DRadAbs.cpp.i
.PHONY : GreensFunction1DRadAbs.i

# target to preprocess a source file
GreensFunction1DRadAbs.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction1DRadAbs.cpp.i
.PHONY : GreensFunction1DRadAbs.cpp.i

GreensFunction1DRadAbs.s: GreensFunction1DRadAbs.cpp.s
.PHONY : GreensFunction1DRadAbs.s

# target to generate assembly for a file
GreensFunction1DRadAbs.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction1DRadAbs.cpp.s
.PHONY : GreensFunction1DRadAbs.cpp.s

GreensFunction2DAbsSym.o: GreensFunction2DAbsSym.cpp.o
.PHONY : GreensFunction2DAbsSym.o

# target to build an object file
GreensFunction2DAbsSym.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction2DAbsSym.cpp.o
.PHONY : GreensFunction2DAbsSym.cpp.o

GreensFunction2DAbsSym.i: GreensFunction2DAbsSym.cpp.i
.PHONY : GreensFunction2DAbsSym.i

# target to preprocess a source file
GreensFunction2DAbsSym.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction2DAbsSym.cpp.i
.PHONY : GreensFunction2DAbsSym.cpp.i

GreensFunction2DAbsSym.s: GreensFunction2DAbsSym.cpp.s
.PHONY : GreensFunction2DAbsSym.s

# target to generate assembly for a file
GreensFunction2DAbsSym.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction2DAbsSym.cpp.s
.PHONY : GreensFunction2DAbsSym.cpp.s

GreensFunction2DRadAbs.o: GreensFunction2DRadAbs.cpp.o
.PHONY : GreensFunction2DRadAbs.o

# target to build an object file
GreensFunction2DRadAbs.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction2DRadAbs.cpp.o
.PHONY : GreensFunction2DRadAbs.cpp.o

GreensFunction2DRadAbs.i: GreensFunction2DRadAbs.cpp.i
.PHONY : GreensFunction2DRadAbs.i

# target to preprocess a source file
GreensFunction2DRadAbs.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction2DRadAbs.cpp.i
.PHONY : GreensFunction2DRadAbs.cpp.i

GreensFunction2DRadAbs.s: GreensFunction2DRadAbs.cpp.s
.PHONY : GreensFunction2DRadAbs.s

# target to generate assembly for a file
GreensFunction2DRadAbs.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction2DRadAbs.cpp.s
.PHONY : GreensFunction2DRadAbs.cpp.s

GreensFunction3D.o: GreensFunction3D.cpp.o
.PHONY : GreensFunction3D.o

# target to build an object file
GreensFunction3D.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3D.cpp.o
.PHONY : GreensFunction3D.cpp.o

GreensFunction3D.i: GreensFunction3D.cpp.i
.PHONY : GreensFunction3D.i

# target to preprocess a source file
GreensFunction3D.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3D.cpp.i
.PHONY : GreensFunction3D.cpp.i

GreensFunction3D.s: GreensFunction3D.cpp.s
.PHONY : GreensFunction3D.s

# target to generate assembly for a file
GreensFunction3D.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3D.cpp.s
.PHONY : GreensFunction3D.cpp.s

GreensFunction3DAbs.o: GreensFunction3DAbs.cpp.o
.PHONY : GreensFunction3DAbs.o

# target to build an object file
GreensFunction3DAbs.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DAbs.cpp.o
.PHONY : GreensFunction3DAbs.cpp.o

GreensFunction3DAbs.i: GreensFunction3DAbs.cpp.i
.PHONY : GreensFunction3DAbs.i

# target to preprocess a source file
GreensFunction3DAbs.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DAbs.cpp.i
.PHONY : GreensFunction3DAbs.cpp.i

GreensFunction3DAbs.s: GreensFunction3DAbs.cpp.s
.PHONY : GreensFunction3DAbs.s

# target to generate assembly for a file
GreensFunction3DAbs.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DAbs.cpp.s
.PHONY : GreensFunction3DAbs.cpp.s

GreensFunction3DAbsSym.o: GreensFunction3DAbsSym.cpp.o
.PHONY : GreensFunction3DAbsSym.o

# target to build an object file
GreensFunction3DAbsSym.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DAbsSym.cpp.o
.PHONY : GreensFunction3DAbsSym.cpp.o

GreensFunction3DAbsSym.i: GreensFunction3DAbsSym.cpp.i
.PHONY : GreensFunction3DAbsSym.i

# target to preprocess a source file
GreensFunction3DAbsSym.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DAbsSym.cpp.i
.PHONY : GreensFunction3DAbsSym.cpp.i

GreensFunction3DAbsSym.s: GreensFunction3DAbsSym.cpp.s
.PHONY : GreensFunction3DAbsSym.s

# target to generate assembly for a file
GreensFunction3DAbsSym.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DAbsSym.cpp.s
.PHONY : GreensFunction3DAbsSym.cpp.s

GreensFunction3DRadAbs.o: GreensFunction3DRadAbs.cpp.o
.PHONY : GreensFunction3DRadAbs.o

# target to build an object file
GreensFunction3DRadAbs.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DRadAbs.cpp.o
.PHONY : GreensFunction3DRadAbs.cpp.o

GreensFunction3DRadAbs.i: GreensFunction3DRadAbs.cpp.i
.PHONY : GreensFunction3DRadAbs.i

# target to preprocess a source file
GreensFunction3DRadAbs.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DRadAbs.cpp.i
.PHONY : GreensFunction3DRadAbs.cpp.i

GreensFunction3DRadAbs.s: GreensFunction3DRadAbs.cpp.s
.PHONY : GreensFunction3DRadAbs.s

# target to generate assembly for a file
GreensFunction3DRadAbs.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DRadAbs.cpp.s
.PHONY : GreensFunction3DRadAbs.cpp.s

GreensFunction3DRadAbsBase.o: GreensFunction3DRadAbsBase.cpp.o
.PHONY : GreensFunction3DRadAbsBase.o

# target to build an object file
GreensFunction3DRadAbsBase.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DRadAbsBase.cpp.o
.PHONY : GreensFunction3DRadAbsBase.cpp.o

GreensFunction3DRadAbsBase.i: GreensFunction3DRadAbsBase.cpp.i
.PHONY : GreensFunction3DRadAbsBase.i

# target to preprocess a source file
GreensFunction3DRadAbsBase.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DRadAbsBase.cpp.i
.PHONY : GreensFunction3DRadAbsBase.cpp.i

GreensFunction3DRadAbsBase.s: GreensFunction3DRadAbsBase.cpp.s
.PHONY : GreensFunction3DRadAbsBase.s

# target to generate assembly for a file
GreensFunction3DRadAbsBase.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DRadAbsBase.cpp.s
.PHONY : GreensFunction3DRadAbsBase.cpp.s

GreensFunction3DRadInf.o: GreensFunction3DRadInf.cpp.o
.PHONY : GreensFunction3DRadInf.o

# target to build an object file
GreensFunction3DRadInf.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DRadInf.cpp.o
.PHONY : GreensFunction3DRadInf.cpp.o

GreensFunction3DRadInf.i: GreensFunction3DRadInf.cpp.i
.PHONY : GreensFunction3DRadInf.i

# target to preprocess a source file
GreensFunction3DRadInf.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DRadInf.cpp.i
.PHONY : GreensFunction3DRadInf.cpp.i

GreensFunction3DRadInf.s: GreensFunction3DRadInf.cpp.s
.PHONY : GreensFunction3DRadInf.s

# target to generate assembly for a file
GreensFunction3DRadInf.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DRadInf.cpp.s
.PHONY : GreensFunction3DRadInf.cpp.s

GreensFunction3DSym.o: GreensFunction3DSym.cpp.o
.PHONY : GreensFunction3DSym.o

# target to build an object file
GreensFunction3DSym.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DSym.cpp.o
.PHONY : GreensFunction3DSym.cpp.o

GreensFunction3DSym.i: GreensFunction3DSym.cpp.i
.PHONY : GreensFunction3DSym.i

# target to preprocess a source file
GreensFunction3DSym.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DSym.cpp.i
.PHONY : GreensFunction3DSym.cpp.i

GreensFunction3DSym.s: GreensFunction3DSym.cpp.s
.PHONY : GreensFunction3DSym.s

# target to generate assembly for a file
GreensFunction3DSym.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/GreensFunction3DSym.cpp.s
.PHONY : GreensFunction3DSym.cpp.s

SphericalBesselGenerator.o: SphericalBesselGenerator.cpp.o
.PHONY : SphericalBesselGenerator.o

# target to build an object file
SphericalBesselGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/SphericalBesselGenerator.cpp.o
.PHONY : SphericalBesselGenerator.cpp.o

SphericalBesselGenerator.i: SphericalBesselGenerator.cpp.i
.PHONY : SphericalBesselGenerator.i

# target to preprocess a source file
SphericalBesselGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/SphericalBesselGenerator.cpp.i
.PHONY : SphericalBesselGenerator.cpp.i

SphericalBesselGenerator.s: SphericalBesselGenerator.cpp.s
.PHONY : SphericalBesselGenerator.s

# target to generate assembly for a file
SphericalBesselGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/SphericalBesselGenerator.cpp.s
.PHONY : SphericalBesselGenerator.cpp.s

findRoot.o: findRoot.cpp.o
.PHONY : findRoot.o

# target to build an object file
findRoot.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/findRoot.cpp.o
.PHONY : findRoot.cpp.o

findRoot.i: findRoot.cpp.i
.PHONY : findRoot.i

# target to preprocess a source file
findRoot.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/findRoot.cpp.i
.PHONY : findRoot.cpp.i

findRoot.s: findRoot.cpp.s
.PHONY : findRoot.s

# target to generate assembly for a file
findRoot.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/findRoot.cpp.s
.PHONY : findRoot.cpp.s

freeFunctions.o: freeFunctions.cpp.o
.PHONY : freeFunctions.o

# target to build an object file
freeFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/freeFunctions.cpp.o
.PHONY : freeFunctions.cpp.o

freeFunctions.i: freeFunctions.cpp.i
.PHONY : freeFunctions.i

# target to preprocess a source file
freeFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/freeFunctions.cpp.i
.PHONY : freeFunctions.cpp.i

freeFunctions.s: freeFunctions.cpp.s
.PHONY : freeFunctions.s

# target to generate assembly for a file
freeFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/freeFunctions.cpp.s
.PHONY : freeFunctions.cpp.s

funcSum.o: funcSum.cpp.o
.PHONY : funcSum.o

# target to build an object file
funcSum.cpp.o:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/funcSum.cpp.o
.PHONY : funcSum.cpp.o

funcSum.i: funcSum.cpp.i
.PHONY : funcSum.i

# target to preprocess a source file
funcSum.cpp.i:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/funcSum.cpp.i
.PHONY : funcSum.cpp.i

funcSum.s: funcSum.cpp.s
.PHONY : funcSum.s

# target to generate assembly for a file
funcSum.cpp.s:
	$(MAKE) -f CMakeFiles/greens_functions.dir/build.make CMakeFiles/greens_functions.dir/funcSum.cpp.s
.PHONY : funcSum.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... greens_functions"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... GreensFunction1DAbsAbs_test"
	@echo "... GreensFunction1DRadAbs_test"
	@echo "... GreensFunction3DSym_test"
	@echo "... GreensFunction1DAbsAbs.o"
	@echo "... GreensFunction1DAbsAbs.i"
	@echo "... GreensFunction1DAbsAbs.s"
	@echo "... GreensFunction1DAbsSinkAbs.o"
	@echo "... GreensFunction1DAbsSinkAbs.i"
	@echo "... GreensFunction1DAbsSinkAbs.s"
	@echo "... GreensFunction1DRadAbs.o"
	@echo "... GreensFunction1DRadAbs.i"
	@echo "... GreensFunction1DRadAbs.s"
	@echo "... GreensFunction2DAbsSym.o"
	@echo "... GreensFunction2DAbsSym.i"
	@echo "... GreensFunction2DAbsSym.s"
	@echo "... GreensFunction2DRadAbs.o"
	@echo "... GreensFunction2DRadAbs.i"
	@echo "... GreensFunction2DRadAbs.s"
	@echo "... GreensFunction3D.o"
	@echo "... GreensFunction3D.i"
	@echo "... GreensFunction3D.s"
	@echo "... GreensFunction3DAbs.o"
	@echo "... GreensFunction3DAbs.i"
	@echo "... GreensFunction3DAbs.s"
	@echo "... GreensFunction3DAbsSym.o"
	@echo "... GreensFunction3DAbsSym.i"
	@echo "... GreensFunction3DAbsSym.s"
	@echo "... GreensFunction3DRadAbs.o"
	@echo "... GreensFunction3DRadAbs.i"
	@echo "... GreensFunction3DRadAbs.s"
	@echo "... GreensFunction3DRadAbsBase.o"
	@echo "... GreensFunction3DRadAbsBase.i"
	@echo "... GreensFunction3DRadAbsBase.s"
	@echo "... GreensFunction3DRadInf.o"
	@echo "... GreensFunction3DRadInf.i"
	@echo "... GreensFunction3DRadInf.s"
	@echo "... GreensFunction3DSym.o"
	@echo "... GreensFunction3DSym.i"
	@echo "... GreensFunction3DSym.s"
	@echo "... SphericalBesselGenerator.o"
	@echo "... SphericalBesselGenerator.i"
	@echo "... SphericalBesselGenerator.s"
	@echo "... findRoot.o"
	@echo "... findRoot.i"
	@echo "... findRoot.s"
	@echo "... freeFunctions.o"
	@echo "... freeFunctions.i"
	@echo "... freeFunctions.s"
	@echo "... funcSum.o"
	@echo "... funcSum.i"
	@echo "... funcSum.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

