all:
	platex GreensFunction2DRadAbs.tex && platex GreensFunction2DRadAbs.tex && dvipdfmx GreensFunction2DRadAbs.dvi

.PHONY: clean
clean:
	rm GreensFunction2DRadAbs.aux GreensFunction2DRadAbs.dvi GreensFunction2DRadAbs.log GreensFunction2DRadAbs.pdf
